import { existsSync, mkdirSync } from "fs";
import { join } from "path";
import type {
  QueueItem,
  CostConfig,
  ImplementationSummary,
  TriageReport,
  HeimdallConfig,
} from "./types";
import type { Logger } from "./logger";
import { QueueManager } from "./queue";
import { NotifyAction } from "./actions/notify";
import { HEIMDALL_DIR, resolveHomePath } from "./config";
import { writePid, writeHeartbeat, clearHeartbeatFiles } from "./heartbeat";

// --- Pure utility functions (tested) ---

export function calculateCost(
  inputTokens: number,
  outputTokens: number,
  costs: CostConfig,
  model: string
): number {
  const pricing = costs[model];
  if (!pricing) return 0;
  return (inputTokens / 1000) * pricing.inputPer1k + (outputTokens / 1000) * pricing.outputPer1k;
}

export interface StreamJsonResult {
  inputTokens: number;
  outputTokens: number;
  cacheTokens: number;
  result: string;
  costUsd: number;
}

export function parseStreamJson(output: string): StreamJsonResult {
  const result: StreamJsonResult = {
    inputTokens: 0,
    outputTokens: 0,
    cacheTokens: 0,
    result: "",
    costUsd: 0,
  };

  for (const line of output.split("\n")) {
    if (!line.trim()) continue;
    try {
      const obj = JSON.parse(line);
      if (obj.usage) {
        result.inputTokens = obj.usage.input_tokens || result.inputTokens;
        result.outputTokens = obj.usage.output_tokens || result.outputTokens;
        result.cacheTokens = obj.usage.cache_read_input_tokens || result.cacheTokens;
      }
      if (obj.total_cost_usd) {
        result.costUsd = obj.total_cost_usd;
      }
      if (obj.result) {
        result.result = obj.result;
      }
    } catch {
      // skip non-JSON lines
    }
  }

  return result;
}

export function formatDuration(seconds: number): string {
  const m = Math.floor(seconds / 60);
  const s = Math.floor(seconds % 60);
  return `${m}m ${s}s`;
}

export function buildImplementationPrompt(
  item: QueueItem,
  triageContent: string,
  worktreePath: string
): string {
  return `You are implementing Jira issue ${item.issueKey}: ${item.title}

## Requirements
${item.description}

## Triage Analysis
${triageContent}

## Working Directory
${worktreePath}

Follow the workflow defined in your system prompt. Start at Gate 1.`;
}

// --- PR body builder ---

export function buildPrBody(
  item: QueueItem,
  summary: ImplementationSummary,
  triageContent: string,
  jiraBaseUrl?: string
): string {
  const jiraLink = jiraBaseUrl
    ? `[${item.issueKey}](${jiraBaseUrl}/browse/${item.issueKey})`
    : item.issueKey;
  const statusIcon = summary.status === "complete" ? "✅" : "⚠️";
  const statusText =
    summary.status === "complete"
      ? "Complete"
      : `Incomplete — ${summary.error || "unknown error"}`;

  return `## Summary
${summary.title}

## Heimdall Report
| Metric | Value |
|--------|-------|
| Jira Issue | ${jiraLink} |
| Confidence | ${summary.triageScore}/9 |
| Size | ${summary.size} |
| Time | Triage: ${formatDuration(summary.timings.triageSeconds)} — Implementation: ${formatDuration(summary.timings.implementationSeconds)} |
| Cost | ~$${summary.cost.totalUsd.toFixed(2)} (input: ${(summary.cost.inputTokens / 1000).toFixed(0)}k, output: ${(summary.cost.outputTokens / 1000).toFixed(0)}k, cache: ${(summary.cost.cacheTokens / 1000).toFixed(0)}k) |
| Model | ${summary.model} |
| Tests | ${summary.tests.passing} passing, ${summary.tests.failing} failing |
| Files changed | ${summary.filesChanged} |

## Status
${statusIcon} ${statusText}

## Triage Analysis
${triageContent}

---
Generated by Heimdall — The All-Seeing PR Guardian`;
}

// --- Worker class (not unit tested — spawns external processes) ---

export class Worker {
  private readonly worktreeDir: string;
  private heartbeatInterval: Timer | null = null;

  constructor(
    private readonly queue: QueueManager,
    private readonly config: HeimdallConfig,
    private readonly notifier: NotifyAction,
    private readonly logger: Logger
  ) {
    this.worktreeDir = resolveHomePath(config.worker.worktreeDir);
    mkdirSync(this.worktreeDir, { recursive: true });
  }

  startHeartbeat(): void {
    const heimdallDir = resolveHomePath(HEIMDALL_DIR);
    writePid(heimdallDir);
    writeHeartbeat(heimdallDir);
    this.heartbeatInterval = setInterval(() => writeHeartbeat(heimdallDir), 10_000);

    const cleanup = () => {
      if (this.heartbeatInterval) clearInterval(this.heartbeatInterval);
      clearHeartbeatFiles(heimdallDir);
    };
    process.on("exit", cleanup);
    process.on("SIGTERM", () => { cleanup(); process.exit(0); });
    process.on("SIGINT", () => { cleanup(); process.exit(0); });
  }

  stopHeartbeat(): void {
    if (this.heartbeatInterval) {
      clearInterval(this.heartbeatInterval);
      this.heartbeatInterval = null;
    }
    clearHeartbeatFiles(resolveHomePath(HEIMDALL_DIR));
  }

  async processNext(): Promise<boolean> {
    const item = await this.queue.pickNext();
    if (!item) {
      this.logger.info("No pending items in queue");
      return false;
    }

    this.logger.info(`Processing ${item.issueKey}: ${item.title}`);
    await this.queue.update(item.issueKey, { status: "in_progress" });

    const worktreePath = join(this.worktreeDir, item.issueKey);
    const branch = `heimdall/${item.issueKey}`;

    try {
      await this.createWorktree(item.cwd, worktreePath, branch);
      await this.queue.update(item.issueKey, { branch });

      let triageContent = "";
      if (existsSync(item.triageReport)) {
        triageContent = await Bun.file(item.triageReport).text();
      }

      const implStart = Date.now();
      const prompt = buildImplementationPrompt(item, triageContent, worktreePath);
      const claudeResult = await this.spawnClaude(prompt, worktreePath, item);
      const implSeconds = (Date.now() - implStart) / 1000;

      const streamResult = parseStreamJson(claudeResult.stdout);
      const model = `claude-${this.config.worker.model}-4-6`;
      const cost = calculateCost(
        streamResult.inputTokens,
        streamResult.outputTokens,
        this.config.costs,
        model
      );

      const filesChanged = await this.countChangedFiles(worktreePath);

      await this.pushBranch(worktreePath, branch);
      const isComplete = claudeResult.exitCode === 0;

      const summary: ImplementationSummary = {
        issueKey: item.issueKey,
        title: item.title,
        triageScore: 0,
        size: "M",
        timings: { triageSeconds: 0, implementationSeconds: implSeconds },
        cost: {
          inputTokens: streamResult.inputTokens,
          outputTokens: streamResult.outputTokens,
          cacheTokens: streamResult.cacheTokens,
          totalUsd: streamResult.costUsd || cost,
        },
        model,
        tests: { passing: 0, failing: 0 },
        filesChanged,
        prUrl: "",
        status: isComplete ? "complete" : "incomplete",
        error: isComplete ? undefined : `Exit code ${claudeResult.exitCode}`,
      };

      const triageJsonPath = item.triageReport.replace(".md", ".json");
      if (existsSync(triageJsonPath)) {
        const triageReport: TriageReport = await Bun.file(triageJsonPath).json();
        summary.triageScore = triageReport.result.total;
        summary.size = triageReport.result.size;
      }

      const jiraSource = this.config.sources.find((s) => s.type === "jira") as
        | import("./types").JiraSourceConfig
        | undefined;
      const prBody = buildPrBody(item, summary, triageContent, jiraSource?.baseUrl);
      const prTitle = `[Heimdall] ${item.issueKey}: ${item.title}`;
      const prUrl = await this.createDraftPr(item.cwd, branch, prTitle, prBody);
      summary.prUrl = prUrl;

      await this.saveRunArtifacts(item.issueKey, summary, triageContent, claudeResult.stdout);

      await this.queue.update(item.issueKey, {
        status: isComplete ? "completed" : "failed",
        prUrl,
      });

      if (isComplete) {
        await this.notifier.notifyWorkerComplete(
          item.issueKey,
          prUrl,
          summary.triageScore,
          `$${summary.cost.totalUsd.toFixed(2)}`,
          formatDuration(implSeconds)
        );
      } else {
        await this.notifier.notifyWorkerFailed(
          item.issueKey,
          `Partial PR opened — ${summary.error}`
        );
      }

      if (isComplete) {
        await this.removeWorktree(item.cwd, worktreePath);
      } else {
        this.logger.warn(`Preserving worktree for failed item: ${worktreePath}`);
      }

      this.logger.info(`${item.issueKey} ${isComplete ? "completed" : "failed"}: ${prUrl}`);
      return true;
    } catch (err) {
      this.logger.error(`Worker error for ${item.issueKey}: ${err}`);
      await this.queue.update(item.issueKey, {
        status: "failed",
        error: String(err),
      });
      await this.notifier.notifyWorkerFailed(item.issueKey, String(err));
      return true;
    }
  }

  private async createWorktree(repoCwd: string, worktreePath: string, branch: string): Promise<void> {
    this.logger.info(`Creating worktree: ${worktreePath} (branch: ${branch})`);
    const proc = Bun.spawn(
      ["git", "worktree", "add", worktreePath, "-b", branch],
      { cwd: repoCwd, stdout: "pipe", stderr: "pipe" }
    );
    const [exitCode, , stderr] = await Promise.all([
      proc.exited,
      new Response(proc.stdout).text(),
      new Response(proc.stderr).text(),
    ]);
    if (exitCode !== 0) {
      throw new Error(`git worktree add failed: ${stderr}`);
    }
  }

  private async spawnClaude(
    prompt: string,
    cwd: string,
    item: QueueItem
  ): Promise<{ stdout: string; stderr: string; exitCode: number }> {
    const args = [
      "claude",
      "-p",
      prompt,
      ...this.config.worker.claudeArgs,
      "--model",
      this.config.worker.model,
      "--max-turns",
      String(this.config.worker.maxTurns),
    ];

    if (item.systemPromptFile) {
      const resolvedPath = resolveHomePath(item.systemPromptFile);
      if (existsSync(resolvedPath)) {
        const content = await Bun.file(resolvedPath).text();
        args.push("--append-system-prompt", content);
        this.logger.info(`Injecting system prompt from ${resolvedPath}`);
      } else {
        this.logger.warn(`systemPromptFile not found: ${resolvedPath}`);
      }
    }

    if (item.allowedTools?.length) {
      args.push("--allowlist-tools", item.allowedTools.join(","));
    }

    this.logger.info(`Spawning Claude in ${cwd}`);
    const proc = Bun.spawn(args, {
      cwd,
      stdout: "pipe",
      stderr: "pipe",
      env: { ...process.env, TERM: "dumb" },
    });

    const [exitCode, stdout, stderr] = await Promise.all([
      proc.exited,
      new Response(proc.stdout).text(),
      new Response(proc.stderr).text(),
    ]);

    return { stdout, stderr, exitCode };
  }

  private async countChangedFiles(worktreePath: string): Promise<number> {
    const proc = Bun.spawn(
      ["git", "diff", "--name-only", "main...HEAD"],
      { cwd: worktreePath, stdout: "pipe", stderr: "pipe" }
    );
    const [exitCode, stdout] = await Promise.all([
      proc.exited,
      new Response(proc.stdout).text(),
      new Response(proc.stderr).text(),
    ]);
    if (exitCode !== 0) {
      const fallback = Bun.spawn(
        ["git", "diff", "--name-only", "--cached"],
        { cwd: worktreePath, stdout: "pipe", stderr: "pipe" }
      );
      const [, fallbackOut] = await Promise.all([
        fallback.exited,
        new Response(fallback.stdout).text(),
        new Response(fallback.stderr).text(),
      ]);
      return fallbackOut.trim().split("\n").filter(Boolean).length;
    }
    return stdout.trim().split("\n").filter(Boolean).length;
  }

  private async pushBranch(worktreePath: string, branch: string): Promise<void> {
    this.logger.info(`Pushing branch: ${branch}`);
    const proc = Bun.spawn(
      ["git", "push", "-u", "origin", branch],
      { cwd: worktreePath, stdout: "pipe", stderr: "pipe" }
    );
    const [exitCode, , stderr] = await Promise.all([
      proc.exited,
      new Response(proc.stdout).text(),
      new Response(proc.stderr).text(),
    ]);
    if (exitCode !== 0) {
      throw new Error(`git push failed: ${stderr}`);
    }
  }

  private async createDraftPr(repoCwd: string, branch: string, title: string, body: string): Promise<string> {
    this.logger.info(`Creating draft PR for ${branch}`);
    const proc = Bun.spawn(
      ["gh", "pr", "create", "--draft", "--title", title, "--body", body, "--head", branch],
      { cwd: repoCwd, stdout: "pipe", stderr: "pipe" }
    );
    const [exitCode, stdout, stderr] = await Promise.all([
      proc.exited,
      new Response(proc.stdout).text(),
      new Response(proc.stderr).text(),
    ]);
    if (exitCode !== 0) {
      throw new Error(`gh pr create failed: ${stderr}`);
    }
    return stdout.trim();
  }

  private async saveRunArtifacts(
    issueKey: string,
    summary: ImplementationSummary,
    triageContent: string,
    implementationLog: string
  ): Promise<void> {
    const runsDir = join(resolveHomePath(HEIMDALL_DIR), "runs", issueKey);
    mkdirSync(runsDir, { recursive: true });
    await Bun.write(join(runsDir, "summary.json"), JSON.stringify(summary, null, 2));
    await Bun.write(join(runsDir, "triage.md"), triageContent);
    await Bun.write(join(runsDir, "implementation.log"), implementationLog);
  }

  private async removeWorktree(repoCwd: string, worktreePath: string): Promise<void> {
    this.logger.info(`Removing worktree: ${worktreePath}`);
    const proc = Bun.spawn(
      ["git", "worktree", "remove", worktreePath, "--force"],
      { cwd: repoCwd, stdout: "pipe", stderr: "pipe" }
    );
    await proc.exited;
  }
}
